version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: choreoai-api
    ports:
      - "8000:8000"
    env_file:
      - ./examples/.env
    environment:
      # Server Configuration
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - ALLOWED_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
